name: MLflow CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: modelling_files/conda.yaml
        activate-environment: mlflow-env
        auto-activate-base: false

    - name: Run Python Training Script Directly
      shell: bash -l {0}
      run: python modelling_files/modelling.py

    - name: Commit and Push Artifacts
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "CHORE: Update model artifacts"
          git push
        fi